# Generated by Django 6.0 on 2025-12-17 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام طرح')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('duration_months', models.IntegerField(verbose_name='مدت (ماه)')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ سود (%)')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='حداقل مبلغ')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='حداکثر مبلغ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'طرح اقساط',
                'verbose_name_plural': 'طرح\u200cهای اقساط',
                'db_table': 'installment_plans',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ کل')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قسط ماهانه')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'تکمیل شده'), ('defaulted', 'معوق'), ('cancelled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='installments.installmentplan', verbose_name='طرح')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'db_table': 'installments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('payment_number', models.IntegerField(verbose_name='شماره قسط')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('due_date', models.DateField(verbose_name='سررسید')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('overdue', 'معوق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='installments.installment', verbose_name='قسط')),
            ],
            options={
                'verbose_name': 'پرداخت قسط',
                'verbose_name_plural': 'پرداخت\u200cهای قسط',
                'db_table': 'installment_payments',
                'ordering': ['due_date'],
                'unique_together': {('installment', 'payment_number')},
            },
        ),
    ]
