# Generated by Django 6.0 on 2025-12-17 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('buy', 'خرید'), ('sell', 'فروش'), ('fee', 'کارمزد'), ('installment', 'قسط'), ('refund', 'بازگشت وجه')], max_length=20, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('amount_irr', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ تومان')),
                ('amount_gold', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='مقدار طلا (گرم)')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('reference_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه مرجع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='transaction_user_id_ced08a_idx'), models.Index(fields=['reference_id'], name='transaction_referen_897c8a_idx')],
            },
        ),
    ]
