# Generated by Django 5.0.1 on 2025-12-18 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='trans_user_created_idx',
            old_name='transaction_user_id_ced08a_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='trans_ref_id_idx',
            old_name='transaction_referen_897c8a_idx',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='trans_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='trans_status_created_idx'),
        ),
    ]
