# Generated by Django 6.0 on 2025-12-17 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order_type', models.CharField(choices=[('buy', 'خرید'), ('sell', 'فروش')], max_length=10, verbose_name='نوع سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('gold_amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار طلا (گرم)')),
                ('gold_price_per_gram', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت هر گرم (تومان)')),
                ('amount_irr', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ کل (تومان)')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='کارمزد')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ نهایی')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اجرا')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
