# Generated by Django 5.0.1 on 2025-12-18 21:19

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/', validators=[apps.core.validators.validate_image_file_extension, apps.core.validators.validate_file_size], verbose_name='تصویر کارت ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[apps.core.validators.validate_image_file_extension, apps.core.validators.validate_file_size], verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/', validators=[apps.core.validators.validate_image_file_extension, apps.core.validators.validate_file_size], verbose_name='تصویر سلفی'),
        ),
    ]
