# Generated by Django 6.0 on 2025-12-17 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('sheba_number', models.CharField(max_length=26, verbose_name='شماره شبا')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('account_holder_name', models.CharField(max_length=200, verbose_name='نام صاحب حساب')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('verified', 'تایید شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_method', models.CharField(max_length=50, verbose_name='روش پرداخت')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه تراکنش')),
                ('gateway_reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='شناسه درگاه')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='deposits/', verbose_name='تصویر رسید')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست واریز',
                'verbose_name_plural': 'درخواست\u200cهای واریز',
                'db_table': 'deposit_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('balance_irr', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='موجودی تومان')),
                ('gold_balance', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='موجودی طلا (گرم)')),
                ('frozen_balance_irr', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='موجودی مسدود شده تومان')),
                ('frozen_gold_balance', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='موجودی مسدود شده طلا (گرم)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('buy_gold', 'خرید طلا'), ('sell_gold', 'فروش طلا'), ('fee', 'کارمزد'), ('refund', 'بازگشت وجه')], max_length=20, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('amount_irr', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ تومان')),
                ('amount_gold', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='مقدار طلا (گرم)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه مرجع')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='کارمزد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه تراکنش')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.bankaccount', verbose_name='حساب بانکی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست\u200cهای برداشت',
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
