# Generated by Django 5.0.1 on 2025-12-18 21:19

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='deposits/', validators=[apps.core.validators.validate_receipt_file], verbose_name='تصویر رسید'),
        ),
    ]
