# Generated by Django 6.0 on 2025-12-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت خرید (تومان)')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت فروش (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'قیمت طلا',
                'verbose_name_plural': 'قیمت\u200cهای طلا',
                'db_table': 'gold_prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت (تومان)')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'تاریخچه قیمت',
                'verbose_name_plural': 'تاریخچه قیمت\u200cها',
                'db_table': 'price_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='price_histo_timesta_3488b1_idx')],
            },
        ),
    ]
